# Generated by Django 4.2.16 on 2025-04-09 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comunas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='core/images/logos')),
                ('fecha_contrato', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_vencimiento_mensualidad', models.DateTimeField(blank=True, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Nacionalidad',
                'verbose_name_plural': 'Nacionalidades',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='precios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Precio',
                'verbose_name_plural': 'Precios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='regiones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_descuentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Descuento',
                'verbose_name_plural': 'Tipos de Descuentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='tipo_empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Empresa',
                'verbose_name_plural': 'Tipos de Empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='sedes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('telefono', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('comuna_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.comunas')),
                ('empresa_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='provincias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=300, null=True)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('region_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.regiones')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='empresa',
            name='precio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.precios'),
        ),
        migrations.CreateModel(
            name='descuentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=300, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo_descuento_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipo_descuentos')),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='comunas',
            name='provincia_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.provincias'),
        ),
    ]
