# Generated by Django 4.2.16 on 2025-04-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sedes',
            old_name='comuna_id',
            new_name='comuna',
        ),
        migrations.RenameField(
            model_name='sedes',
            old_name='empresa_id',
            new_name='empresa',
        ),
    ]
