# Generated by Django 4.2.16 on 2025-04-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_comuna_id_sedes_comuna_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comunas',
            old_name='provincia_id',
            new_name='provincia',
        ),
        migrations.RenameField(
            model_name='descuentos',
            old_name='tipo_descuento_id',
            new_name='tipo_descuento',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='precio_id',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='provincias',
            old_name='region_id',
            new_name='region',
        ),
    ]
