# Generated by Django 4.2.16 on 2025-04-11 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_remove_comunas_provincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='colegio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Colegio',
                'verbose_name_plural': 'Colegios',
                'db_table': 'colegio',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Comuna',
                'verbose_name_plural': 'Comunas',
                'db_table': 'comunas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=150)),
                ('razonsocial', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('logo', models.ImageField(upload_to='core/images/logos')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('nacionalidad', models.CharField(max_length=150)),
                ('moneda', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'paises',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='representante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('comunas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comuna_representante', to='core.comuna')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='empresa_representante', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'representante',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pais_region', to='core.pais')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'db_table': 'regiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='region_provincia', to='core.region')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincias',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='pais',
            index=models.Index(fields=['id'], name='idx_pais_titulo'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comuna_empresa', to='core.comuna'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='provincia_comuna', to='core.provincia'),
        ),
        migrations.AddField(
            model_name='colegio',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comuna_colegio', to='core.comuna'),
        ),
        migrations.AddIndex(
            model_name='representante',
            index=models.Index(fields=['id'], name='idx_representante_titulo'),
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['id'], name='idx_region_titulo'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['id'], name='idx_provincia_titulo'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['id'], name='idx_empresa_titulo'),
        ),
        migrations.AddIndex(
            model_name='comuna',
            index=models.Index(fields=['id'], name='idx_comuna_titulo'),
        ),
        migrations.AddIndex(
            model_name='colegio',
            index=models.Index(fields=['id'], name='idx_colegio_titulo'),
        ),
    ]
