# Generated by Django 4.2.16 on 2025-04-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_colegio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colegio',
            options={'ordering': ['id'], 'verbose_name': 'Colegio', 'verbose_name_plural': 'Colegios'},
        ),
    ]
