# Generated by Django 4.2.16 on 2025-04-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_colegio_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pais',
            table='pais',
        ),
    ]
