# Generated by Django 4.2.16 on 2025-04-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pais_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pais',
            table='core_pais',
        ),
    ]
