# Generated by Django 4.2.16 on 2025-04-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pais_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='colegio',
            table='core_colegio',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='core_comunas',
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='core_empresa',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='core_provincias',
        ),
        migrations.AlterModelTable(
            name='region',
            table='core_regiones',
        ),
        migrations.AlterModelTable(
            name='representante',
            table='core_representante',
        ),
    ]
