# Generated by Django 4.2.16 on 2025-04-11 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_colegio_table_alter_comuna_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_colegio', to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincia_comuna', to='core.provincia'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_empresa', to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_provincia', to='core.region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_region', to='core.pais'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='comunas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comuna_representante', to='core.comuna'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_representante', to='core.empresa'),
        ),
    ]
